---
- name: Git | Ensure cgit install
  homebrew:
    name:
      - cgit

- name: Git | Ensure cgit config
  template:
    src: cgitrc.j2
    dest: /usr/local/etc/cgitrc
    mode: 0644
    owner: "{{ ansible_user }}"
    group: admin

- name: Git | Ensure cgit script
  copy:
    src: git.sh
    dest: /usr/local/var/www/cgi-bin/
    mode: 0755
    owner: "{{ ansible_user }}"
    group: admin

- name: Git | Ensure git repositories
  include_role:
    name: afakeman.utility.git-repo
  loop: "{{ git_repo_list }}"
  vars:
    repo_name: "{{ repo.name }}"
    repo_hooks: "{{ repo.hooks }}"
  loop_control:
    loop_var: repo
