---
- name: Git | {{ repo_name }} | Check if directory exists
  stat:
    path: "{{ repo_base_path }}/{{ repo_name }}"
  register: _repo_stat

- name: Git | {{ repo_name }} | Ensure repository exists
  file:
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0755
    dest: "{{ repo_base_path }}/{{ repo_name }}"

- name: Git | {{ repo_name }} | Check if repository exists and is bare
  command:
    cmd: git rev-parse --is-bare-repository
    chdir: "{{ repo_base_path }}/{{ repo_name }}"
  changed_when: false
  check_mode: false
  failed_when:
    - _git_state.rc != 0
    - "_git_state.stderr != 'fatal: not a git repository (or any of the parent directories): .git'"
  register: _git_state
  when: _repo_stat.stat.exists

- name: Git | {{ repo_name }} | Fail if repository exists but not bare
  assert:
    that: (not _repo_stat.stat.exists) or (_git_state.stdout != "false")
    msg: "Repository {{ repo_base_path }}/{{ repo_name }} exists and is not bare"

- name: Git | {{ repo_name }} | Ensure repository
  when: "(not _repo_stat.stat.exists) or _git_state.rc != 0"
  block:
    - name: Git | {{ repo_name }} | Ensure server repository
      git:
        repo: "{{ repo_upstream }}"
        dest: "{{ repo_base_path }}/{{ repo_name }}"
        remote: upstream
        bare: true
        update: false
        accept_hostkey: yes
      when: "repo_upstream"

    - name: Git | {{ repo_name }} | Ensure bare repository
      command:
        cmd: git init {{ repo_name }} --bare
        chdir: "{{ repo_base_path }}"
      when: "not repo_upstream"

- name: Git | {{ repo_name }} | Ensure post-update hook to work with dumb HTTP protocol
  copy:
    dest: "{{ repo_base_path }}/{{ repo_name }}/hooks/post-update"
    content: |
      #!/bin/sh

      exec git update-server-info
    owner: "{{ ansible_user }}"
    group: admin
    mode: 0755

- name: Git | {{ repo_name }} | Ensure hooks
  copy:
    dest: "{{ repo_base_path }}/{{ repo_name }}/hooks/{{ item.key }}"
    content: "{{ item.value }}\n"
    owner: "{{ ansible_user }}"
    group: admin
    mode: 0755
  loop: "{{ repo_hooks | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
