dependencies:
  - name: afakeman.utility.nginx-server
    vars:
      server_name: oblivion
      subdomain: "{{ oblivion_subdomain_idn }}"
      snippet: |
        location / {
            proxy_pass http://127.0.0.1:8533/cgi-bin/oblivion.sh$uri$is_args$args;
        }
