dependencies:
  - name: afakeman.utility.nginx-server
    vars:
      server_name: oblivion
      subdomain: "{{ oblivion_subdomain_idn }}"
      alt_subdomain: oblivion
      snippet: |
        location / {
            proxy_set_header user-agent $http_host;
            proxy_pass http://127.0.0.1:8533/cgi-bin/oblivion.sh$uri$is_args$args;
        }

        location ~ ^/voice/(.*)\.wav {
            proxy_pass http://127.0.0.1:8533/cgi-bin/oblivion_tts.sh/$1$is_args$args;
        }
