- name: Check if variables are set
  assert:
    that:
      - server_name is defined
      - subdomain is defined
      - domain is defined
    quiet: true

- name: Copy the template to the nginx directory
  template:
    src: "server.conf.j2"
    dest: "/usr/local/etc/nginx/conf.d/{{ server_name }}.conf"
  notify: reload nginx
  register: _nginx

- name: Check nginx configuration
  command: /usr/local/bin/nginx -T
  become: true
  when: _nginx.changed
